###
POST http://localhost:8080/update/gauge/Alloc/124.6
Content-Type: text/plain

> {%
client.test("correct request", function() {
  client.assert(response.status === 200, "Response status is not 200");
})
 %}


###
POST http://localhost:8080/update/gauge1/Alloc/124.6
Content-Type: text/plain

> {%
client.test("correct request", function() {
  client.assert(response.status !== 200, "Response status is 200");
})
 %}

###
GET http://localhost:8080/update/gauge/Alloc/124.6
Content-Type: text/plain

> {%
client.test("correct request", function() {
  client.assert(response.status !== 200, "Response status is 200");
})
 %}

### JSON
POST http://localhost:8080/update/
Content-Type: application/json

{
  "id":"GCSys",
  "type":"counter",
  "delta":100
}

> {%
client.test("correct request", function() {
  client.assert(response.status !== 200, "Response status is 200");
})
 %}
